/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_techrecipes_online_jniutils_SystemDateUtility */

#ifndef _Included_org_techrecipes_online_jniutils_SystemDateUtility
#define _Included_org_techrecipes_online_jniutils_SystemDateUtility
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_techrecipes_online_jniutils_SystemDateUtility
 * Method:    getSystemTime
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_techrecipes_online_jniutils_SystemDateUtility_getSystemTime
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
