package org.techrecipes.online.stockstreamer;
/**
 * Created by sjayapal on 12/22/2016.
 */
public class StockDetailData {
    /**
     * id : 304466804484872
     * t : GOOG
     * e : NASDAQ
     * l : 790.19
     * l_fix : 790.19
     * l_cur : 790.19
     * s : 0
     * ltt : 11:56AM EST
     * lt : Dec 22, 11:56AM EST
     * lt_dts : 2016-12-22T11:56:58Z
     * c : -4.37
     * c_fix : -4.37
     * cp : -0.55
     * cp_fix : -0.55
     * ccol : chr
     * pcls_fix : 794.56
     * {"results":[{"open":"103.250000","high":"103.630000","low":"102.600000","volume":"3561874.000000","average_volume_2_weeks":"38030278.555600","average_volume":"31987244.048000","high_52_weeks":"116.180000","dividend_yield":"1.703700","low_52_weeks":"83.830000","market_cap":"800793600000.000000","pe_ratio":"42.950207","shares_outstanding":"7680000000.000000","description":"Microsoft Corp. engages in the development and support of software, services, devices, and solutions. Its products includes operating systems; cross-device productivity applications; server applications; business solution applications; desktop and server management tools; software development tools; and video games. It also offers personal computers, tablets, gaming and entertainment consoles, other intelligent devices, and related accessories. It operates through the following business segments: Productivity and Business Processes; Intelligent Cloud; and More Personal Computing. The Productivity and Business Processes segment is comprised of products and services in the portfolio of productivity, communication, and information services of the company spanning a variety of devices and platform. The Intelligent Cloud segment refers to the public, private, and hybrid serve products and cloud services of the company which can power modern business. The More Personal Computing segment encompasses the products and services such as windows operating system, devices, gaming platform, and search engines. The company was founded by William Henry Gates III in 1975 and is headquartered in Redmond, WA.","instrument":"https://api.robinhood.com/instruments/50810c35-d215-4866-9758-0ada4ac79ffa/","ceo":"Satya Nadella","headquarters_city":"Redmond","headquarters_state":"Washington","sector":"Technology Services","industry":"Packaged Software","num_employees":131000,"year_founded":1975},{"open":"143.150000","high":"143.250000","low":"140.840000","volume":"3202350.000000","average_volume_2_weeks":"25200799.777800","average_volume":"27978494.980000","high_52_weeks":"218.620000","dividend_yield":"0.000000","low_52_weeks":"123.020000","market_cap":"414372790000.000000","pe_ratio":"21.527610","shares_outstanding":"2873000000.000000","description":"Facebook, Inc. engages in the development of social media applications for people to connect through mobile devices, personal computers, and other surfaces. It enables users to share opinions, ideas, photos, videos, and other activities online. Its products include Facebook, Instagram, Messenger, WhatsApp, and Oculus. The company was founded by Mark Elliot Zuckerberg, Dustin Moskovitz, Chris R. Hughes, Andrew McCollum, and Eduardo P. Saverin on February 4, 2004 and is headquartered in Menlo Park, CA.","instrument":"https://api.robinhood.com/instruments/ebab2398-028d-4939-9f1d-13bf38f81c50/","ceo":"Mark Elliot Zuckerberg","headquarters_city":"Menlo Park","headquarters_state":"California","sector":"Technology Services","industry":"Internet Software Or Services","num_employees":25105,"year_founded":2004},{"open":"334.000000","high":"340.270000","low":"331.790000","volume":"915309.000000","average_volume_2_weeks":"7869034.222200","average_volume":"8651926.556000","high_52_weeks":"387.460000","dividend_yield":"0.000000","low_52_weeks":"244.590100","market_cap":"58084300300.000000","pe_ratio":null,"shares_outstanding":"171578000.000000","description":"Tesla, Inc. engages in the design, development, manufacture, and sale of fully electric vehicles, energy generation and storage systems. It also provides vehicle service centers, supercharger station, and self-driving capability. The firm operates through Automotive, and Energy Generation and Storage segments. The Automotive segment includes the design, development, manufacture and sale of electric vehicles. The Energy Generation and Storage segment includes the design, manufacture, installation, sale, and lease of stationary energy storage products and solar energy systems, and sale of electricity generated by its solar energy systems to customers. The company was founded by Jeffrey B. Straubel, Elon Reeve Musk, Martin Eberhard, and Marc Tarpenning on July 1, 2003 and is headquartered in Palo Alto, CA.","instrument":"https://api.robinhood.com/instruments/e39ed23a-7bd1-4587-b060-71988d9ef483/","ceo":"Elon Reeve Musk","headquarters_city":"Palo Alto","headquarters_state":"California","sector":"Consumer Durables","industry":"Motor Vehicles","num_employees":37543,"year_founded":2003}]}
     */
    @com.google.gson.annotations.SerializedName("id")
    private String stockid;
    @com.google.gson.annotations.SerializedName("t")
    private String stockTickr;
    @com.google.gson.annotations.SerializedName("e")
    private String stockExchange;
    @com.google.gson.annotations.SerializedName("l")
    private String currentdaylow;
    @com.google.gson.annotations.SerializedName("l_fix")
    private String todayFixed;
    @com.google.gson.annotations.SerializedName("lt_dts")
    private String stockPriceDateTime;
    @com.google.gson.annotations.SerializedName("c")
    private String todayChange;
    private String businessName;
    public String getBusinessName() {
        return businessName;
    }
    public void setBusinessName(String businessName) {
        this.businessName = businessName;
    }
    public String getStockid() {
        return stockid;
    }
    public void setStockid(String stockid) {
        this.stockid = stockid;
    }
    public String getStockTickr() {
        return stockTickr;
    }
    public void setStockTickr(String stockTickr) {
        this.stockTickr = stockTickr;
    }
    public String getStockExchange() {
        return stockExchange;
    }
    public void setStockExchange(String stockExchange) {
        this.stockExchange = stockExchange;
    }
    public String getCurrentdaylow() {
        return currentdaylow;
    }
    public void setCurrentdaylow(String currentdaylow) {
        this.currentdaylow = currentdaylow;
    }
    public String getTodayFixed() {
        return todayFixed;
    }
    public void setTodayFixed(String todayFixed) {
        this.todayFixed = todayFixed;
    }
    public String getStockPriceDateTime() {
        return stockPriceDateTime;
    }
    public void setStockPriceDateTime(String stockPriceDateTime) {
        this.stockPriceDateTime = stockPriceDateTime;
    }
    public String getTodayChange() {
        return todayChange;
    }
    public void setTodayChange(String todayChange) {
        this.todayChange = todayChange;
    }
}
